config/routes.rb
Rails.application.routes.draw do
  root to: "drafts#index"

  resources :players
  resources :drafts
  resources :teams
  resources :picks

end

app/models/player.rb
class Player < ActiveRecord::Base
	validates :name, :presence => true
	validates :team, :presence => true
	validates :points_2013, :presence => true
	validates :bye_week, :presence => true
	validates :adp, :presence => true
	validates :tier, :presence => true
	validates :position, :presence => true
	validates :beer_value, :presence => true

	has_attached_file :avatar, :styles => { :medium => "229x200>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  scope :master, -> { where(master: true) }
  scope :copy, -> { where(master: false) }

  has_many :picks
  has_many :teams, through: :picks

end

app/models/team.rb
class Team < ActiveRecord::Base

	belongs_to :draft
	has_many :picks
	has_many :players, through: :picks

  scope :master, -> { where(master: true) }
  scope :copy, -> { where(master: false) }

  def roster
  	roster = []

  	Pick.all.each do |pick|
  		if pick.team_id == self.id
  			roster << pick.player
  		end
  	end
  	roster
  end

  def depth(position)
    players = []

    self.roster.each do |player|
      if player.position == position
        players << player
      end
    end
    players

  end

  def depth_count(position)
    self.depth(position).length
  end

  def flex_count
    return (depth_count('HB') + depth_count('WR') + depth_count('TE'))
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    if params[:query]
      @players = Player.basic_search(params[:query])
    else
      @players = Player.all
    end
    @master_players = @players.master
    @copied_players = @players.copy
  end

  def show
    @player = Player.find(params[:id])
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    @player.update(player_params)
    redirect_to players_path
  end

  def new
    @player = Player.new
    render('new.html.erb')
  end

  def create
    @player = Player.create(player_params)
    @player.save
    redirect_to('/players')
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy
    redirect_to('/players')
  end

private

  def player_params
    params.require(:player).permit(:name, :team, :points_2013, :bye_week, :adp, :position, :beer_value, :drafted, :id, :avatar, :master)
  end

end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
<%if 2 == 1%>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%end%>

  <div class="fields">

    <div class="form-group">
      <%= f.label "Player Name:" %>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
      <%= f.label "Player Position:" %>
      <%= f.text_field :position %>
    </div>
    <div class="form-group">
      <%= f.label "Player Team:" %>
      <%= f.text_field :team %>
    </div>
    <div class="form-group">
      <%= f.label "Fantasy Points 2013:" %>
      <%= f.text_field :points_2013 %>
    </div>
    <div class="form-group">
      <%= f.label "Bye Week:" %>
      <%= f.text_field :bye_week %>
    </div>
    <div class="form-group">
      <%= f.label "ADP:" %>
      <%= f.text_field :adp %>
    </div>
    <div class="form-group">
      <%= f.label "Beer Value:" %>
      <%= f.text_field :beer_value %>
    </div>
    <div class="form-group">
      <%= f.label "Master Status:" %>
      <%= f.text_field :master %>
    </div>
    <%= f.file_field :avatar %>
    </br>

    <%= f.submit 'Submit Player', :class => "btn btn-info" %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to "players", players_path %>

app/views/players/index.html.erb
<h1> Players </h1>
<div class='row'>
	<div class='col-lg-6'>
		<form action='/players?query' method='get' id='search'>
			  <input id="search" type='text' name='query'>
			  <button> Search players</button>


		</form>
					  <%= link_to 'Clear', players_path %>

			<h2> Master List: </h2>


			<% @master_players.each do |player| %>
				<ul id='player_index_list'>
					<li>
						<%= link_to player.name, edit_player_path(player) %></br>
					</li>
						<p class='under_player_options'> <%= link_to 'Edit Player', edit_player_path(player), :class => "btn btn-info" %><%= link_to 'Remove Player', player, method: :delete, :class => "btn btn-danger",  data: { confirm: 'Are you sure?' } %> </p>
				</ul>
			<% end %>


	</div>

	<div class='col-lg-6'>
		<h2> Copies: </h2>

		<table>
			<tr>
				<th>Name</th>
			</tr>
			<% @copied_players.each do |player| %>
				<tr>
					<td> <%= check_box_tag 'player_ids[]', player.id %> </td>
					<td> <%= player.name %> </td>
					<td> <%= link_to 'Edit', edit_player_path(player) %> </td>
					<td> <%= link_to 'Destroy', player, method: :delete %> </td>
				</tr>
			<% end %>
		</table>
	</div>
</div>


<%= link_to "New Player", new_player_path, :class => "btn btn-success" %>

app/views/players/new.html.erb
<h1>Add new player:</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>