config/routes.rb
Rails.application.routes.draw do
  root to: "drafts#index"

  resources :players
  resources :drafts
  resources :teams
  resources :picks

end

app/models/draft.rb
class Draft < ActiveRecord::Base

	has_many :teams
	has_many :picks
	has_many :players, through: :picks

	accepts_nested_attributes_for :picks

	validates :draft_position, :presence => true
	validates :number_of_teams, :presence => true
	validates :PPTD, :presence => true
	validates :PPR, :presence => true
	validates :Number_of_starting_QBs, :presence => true
	validates :Number_of_starting_HBs, :presence => true
	validates :Number_of_starting_WRs, :presence => true
	validates :Number_of_starting_FLEX, :presence => true
	validates :draft_type, :presence => true
	validates :keeper, :presence => true
	validates :ranking_method, :presence => true
	validates :rounds, :presence => true
	validates :current_pick, :presence => true

	after_create :set_teams

	def set_teams
		@teams = []
		Team.where(master: true).each do |team|
			if team.draft_position <= self.number_of_teams
				@teams << Team.create(:team_name => team.team_name, :draft_position => team.draft_position, :draft_id => self.id, :master => false)
			end
		end
		@teams
	end

	def set_players
		Player.all
	end

	def team_at(pick)
		return self.set_order[pick - 1]
	end

	def teams
		teams = []
		Team.all.each do |team|
			if team.draft_id == self.id
				teams << team
			end
		end
		teams
	end

	def available_players
		@drafted_players = self.drafted_players
		@available_players = []

		self.set_players.each do |player|
			if drafted_players.index(player) == nil
				@available_players << player
			end
		end
			@available_players
	end

	def drafted_players
		@drafted_players = []
		Pick.all.each do |pick|
			if pick.draft_id == self.id
				@drafted_players << pick.player
			end
		end
		@drafted_players
	end

	def set_order
		@order = []

		self.rounds.times do |number|
			if number.even?
				self.teams.each do |team|
					@order << team
				end
			else
				self.teams.reverse.each do |team|
					@order << team
				end
			end
		end
		@order
	end

	def updraft
		increment(:current_pick)
	end

  def best_available
    best_players_available = []

    if self.ranking_method == 'beer_value'
      best_players_available = self.available_players.sort { |b,a| a.beer_value <=> b.beer_value }
    end

    return best_players_available[0], best_players_available[1], best_players_available[2]
  end

  def current_(round_or_pick)
		results = self.current_pick.divmod(self.number_of_teams)

		current_round = results[0]
		current_pick_in_round = results[1]

		if round_or_pick == 'round'
			if current_pick_in_round == 0
				current_round
			else
				current_round + 1
			end
		else
			if current_pick_in_round == 0
				self.number_of_teams
			else
				current_pick_in_round
			end
		end
  end

  def user_turn
  	return self.current_pick == self.draft_position
  end

  def advance_draft
  	player_to_be_drafted = Best_available.find(self)
  	n_pick = Pick.create(:player_id => player_to_be_drafted.id, :team_id => self.team_at(self.current_pick).id, :draft_id => self.id, :draft_position => self.current_pick)
  end
end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController
  def index
    @drafts = Draft.all
  end

  def show
    @draft = Draft.find(params[:id])
    @players = @draft.set_players
    @teams = @draft.teams
    @current_team = @draft.teams[0]
    @available_players = @draft.available_players
    @drafted_players = @draft.drafted_players
    @best_available = @draft.best_available
    @order = @draft.set_order
    @pick = Pick.new
  end

  def edit
    @draft = Draft.find(params[:id])
  end

  def update
    # redirect_to session.delete(:return_to)
    @draft = Draft.find(params[:id])
    @draft.update(draft_params)
    redirect_to draft_path(@draft)
    # session[:return_to] = request.referer
  end

  def create
    @draft = Draft.create(draft_params)

    if @draft.save
      redirect_to draft_path(@draft)
    else
      render 'new'
    end

  end


  def new
    @draft = Draft.new
  end

private

  def draft_params
    params.require(:draft).permit(:draft_position, :number_of_teams, :PPTD, :PPR, :Number_of_starting_QBs, :Number_of_starting_HBs, :Number_of_starting_WRs, :Number_of_starting_FLEX, :draft_type, :keeper, :ranking_method, :rounds, :current_pick)
  end

  def player_params
    params.require(:player).permit(:name, :team, :points_2013, :bye_week, :adp, :tier, :position, :beer_value, :id, :avatar, :master)
  end

end

app/views/drafts/_form.html.erb
<%= form_for(@draft) do |f| %>
    <div class="form-group">
      <%= f.label "Draft Position" %>
      <%= f.number_field :draft_position %>
    </div>
    <div class="form-group">
      <%= f.label "Draft Type:" %>
      <%= f.text_field :draft_type %>
    </div>
    <div class="form-group">
      <%= f.label "Number of Teams:" %>
      <%= f.number_field :number_of_teams %>
    </div>
    <div class="form-group">
      <%= f.label "Points Per TD:" %>
      <%= f.number_field :PPTD %>
    </div>
    <div class="form-group">
      <%= f.label "Points Per Reception:" %>
      <%= f.number_field :PPR %>
    </div>
    <div class="form-group">
      <%= f.label "Number of Starting QBs:" %>
      <%= f.number_field :Number_of_starting_QBs %>
    </div>
    <div class="form-group">
      <%= f.label "Number of Starting HBs:" %>
      <%= f.number_field :Number_of_starting_HBs %>
    </div>
    <div class="form-group">
      <%= f.label "Number of Starting WRs:" %>
      <%= f.number_field :Number_of_starting_WRs %>
    </div>
    <div class="form-group">
      <%= f.label "Number of Starting FLEX players:" %>
      <%= f.number_field :Number_of_starting_FLEX %>
    </div>
    <div class="form-group">
      <%= f.label "Keepers?" %>
      <%= f.text_field :keeper %>
    </div>
    <div class="form-group">
      <%= f.label "Ranking Method?" %>
      <%= f.text_field :ranking_method %>
    </div>
    <div class="form-group">
      <%= f.label "Rounds" %>
      <%= f.text_field :rounds %>
    </div>

    <%= f.submit 'Add Draft', :class => "btn btn-info" %>
<% end %>

app/views/drafts/edit.html.erb
<div id='new_draft_landing'>
	<h1>Enter Your Settings!</h1>
</div>

<%= render('form') %>

app/views/drafts/index.html.erb
<% @drafts.each do |draft| %>
	<ul>
		<li> <%= link_to draft.id, edit_draft_path(draft) %> </li>
	</ul>
<% end %>


<%= link_to "New Draft", new_draft_path, :class=> "btn btn-default" %>

app/views/drafts/new.html.erb
<h1>New Draft</h1>

<%= render('form') %>

app/views/drafts/new.js.erb
$('.new_pick').hide();

app/views/drafts/show.html.erb
<h1> DRAFT </h1>
<p> <%= @current_team.team_name %> is drafting  </p>

<h3> Best Available </h3>
<ul>


<% @best_available.each do |player| %>
  <li> <%= player.name %> </li>

  <%= link_to 'draft', new_pick_path, class: 'new_pick', remote: true %>

<% end %>
</ul>